# This is a problem from the Project Euler Website
# http://projecteuler.net/
#
# Euler Problem #045
#
# Problem:  Find the next triangle number that is also pentagonal and hexagonal.
#
# Hint:     Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
#           Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#           Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
#           Hexagonal 	  	Hn=n(2n-1) 	  	1, 6, 15, 28, 45, ...
#
#           It can be verified that T285 = P165 = H143 = 40755.
#
# Written by Chris Gilmer
# Solved:   10/28/2008
# Answer:   1533776805
#
# Notes:

from factor import *

if __name__ == '__main__':

    num = 285
    
    #print triagonal(285), pentagonal(165), hexagonal(143)
    
    for n in range(num+1,10**6):
        number = triagonal(n)
        if isPentagonal(number) and isHexagonal(number):
	    break

    print '\n\tTriagonal number %s equals %s and is also pentagonal and hexagonal\n' % (n, number)
