# This is a problem from the Project Euler Website
# http://projecteuler.net/
#
# Euler Problem #044
#
# Problem:  Find the pair of pentagonal numbers, Pj and Pk, for which their
#           sum and difference is pentagonal and D = |Pk - Pj| is minimised;
#           what is the value of D?
#
# Hint:     Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2.
#           The first ten pentagonal numbers are:
#
#           1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
#           It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
#           difference, 70-22 = 48, is not pentagonal.
#
# Written by Chris Gilmer
# Solved:   10/27/2008
# Answer:   5482660
#
# Notes:

from math import *

def pentagonal(num):
    return num*(3*num-1)/2

def isPentagonal(num):
    pent = (1 + sqrt(1 + 24*num))/6
    if pent % 1 == 0:
        return True
    else:
        return False

if __name__ == '__main__':

    D = 10000000

    for k in range(1,10000):
        Pk = pentagonal(k)
        
        for j in range(1,10000):
            Pj = pentagonal(j)
            
            Psum = Pk + Pj
            if isPentagonal(Psum):

                Pdif = abs(Pk - Pj)
                if isPentagonal(Pdif):
                    if Pdif < D:
                        D = Pdif
                        print Pk, Pj, Pdif

    print D


    
