# This is a problem from the Project Euler Website
# http://projecteuler.net/
#
# Euler Problem #029
#
# Problem:  How many distinct terms are in the sequence generated by a^b for
#           2<=a<=100 and 2<=b<=100?
#
# Hint:     Consider all integer combinations of a^b for 2<=a<=5 and 2<=b<=5:
#
#           2^2=4, 2^3=8, 2^4=16, 2^5=32
#           3^2=9, 3^3=27, 3^4=81, 3^5=243
#           4^2=16, 4^3=64, 4^4=256, 4^5=1024
#           5^2=25, 5^3=125, 5^4=625, 5^5=3125
#
#           If they are then placed in numerical order, with any repeats
#           removed, we get the following sequence of 15 distinct terms:
#
#           4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
#
# Written by Chris Gilmer
# Solved:   10/27/2008
# Answer:   9183
#
# Notes:

if __name__ == '__main__':

    alim = 100
    blim = 100
    numlist = []

    for a in range(2,alim+1):
        for b in range(2,blim+1):
            if not numlist.__contains__(a**b):
                numlist.append(a**b)
    
    print '\n\tThere are %s distinct terms generated for a^b' % len(numlist)
    print '\tWith limits 2<=a<=%s and 2<=b<=%s\n' % (alim,blim)
